### ISSUE TITLE
Is renderCachedGirafe possible?

### ISSUE THREAD

**Issue by philstraforelli** [davidgohel/ggiraph#128]
I just recently learned about `renderCachedPlot()` made available in version v1.2 of Shiny. I'm just curious if it's possible to have a similar to utilize that ability in `ggiraph`?

**Comment by cderv** [comment]
Just to add some context that relates to this

From the keynote talk of Joe Cheng at Rstudio conf, I understood that next version of shiny could have a generic approach with a `renderCached` function with a generic mechanism instead of `renderCached*`, `*` being each type of rendered content. 
The shiny team is thinking about it to make it compatible with htmlwidget in general.

I found no issue open on this in shiny repo though 🤔

**Comment by davidgohel** [comment]
Hi

Thanks @cderv !

@philstraforelli I think that is is wiser to wait and see what rstudio will offer as options with htmlwidgets. For now I am closing that issue and maybe reopen it later if necessary :)

David

**Comment by crotman** [comment]
Do you think it is better to wait a little more?

**Comment by sigmapi** [comment]
> Do you think it is better to wait a little more?

Irony never helps, especially if you're interested in others implementing a feature.

Nevertheless, it'll be a useful feature to have.

**Comment by crotman** [comment]
I was not being ironic. Sorry if I could not make myself clear. I think this package is awesome.

**Comment by sigmapi** [comment]
> I was not being ironic. Sorry if I could not make myself clear. I think this package is awesome.

Ok, then my bad, all is fine.

**Comment by crotman** [comment]
> > I was not being ironic. Sorry if I could not make myself clear. I think this package is awesome.
> 
> Ok, then my bad, all is fine.

No. It´s my fault. I was not being ironic but maybe I should have done some research if there are any news about cache and htmlwidgets before asking
