### ISSUE TITLE
padding remains at bottom of graph 

### ISSUE THREAD

**Issue by zoowalk** [davidgohel/ggiraph#153]
Many thanks for your very helpful package.

I am removing a plot's padding with the `sizingPolicy `argument. However, when saving the graph as a htmlwidget a margin or some padding (?) remains at the bottom.  Here I used the background color red to make it visible. I subsequently insert the graph in a blogdown post and the resulting/remaining space is somewhat an issue.

``` r
library(tidyverse)
library(ggiraph)
library(htmlwidgets)

my_plot <- mtcars %>% 
  rownames_to_column(., var="name") %>% 
  ggplot()+
  geom_point_interactive(aes(x=wt,
                             y=qsec,
                             tooltip=name))

my_interactive_plot <- girafe(code=print(my_plot))

x <- girafe_options(x = my_interactive_plot,
                    sizingPolicy(padding = "0px"))

saveWidget(x, file="my_widget2.html",
                        background = "red")
```

<img width="954" alt="padding" src="https://user-images.githubusercontent.com/9595585/68297627-bd0c8f00-0097-11ea-9aa2-64e2caa7b695.PNG">

<sup>Created on 2019-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by davidgohel** [comment]
Hi,

I don't see any issue there but my understanding may be wrong.

Arguments `width_svg` and `height_svg` are the width and height of the graphics region in inches. The default values are 6 and 5 inches. This will define the aspect ratio of the graphic as it will be used to define viewbox attribute of the SVG result.

If using `width_svg=5` and `height_svg=5`, the aspect ratio will be one. In a square region, the background will not appear. 

<img width="581" alt="Capture d’écran 2019-11-12 à 11 38 18" src="https://user-images.githubusercontent.com/4331618/68665005-94761080-0541-11ea-866a-66272e884013.png">


In a non square region, the background will appear because the graphic will be adjusted regarding to width.

<img width="406" alt="Capture d’écran 2019-11-12 à 11 38 32" src="https://user-images.githubusercontent.com/4331618/68665017-993ac480-0541-11ea-908c-1fe7265e04f7.png">




Why are you using `saveWidget` for your blog? `girafe` objects are htmlwidgets and render easily with only print method in a R markdown document.

**Comment by zoowalk** [comment]
Many thanks for getting back to me!
I am using `saveWidget `because I produce the plot in a differen R project and subsequently import it into my blogdown blogpost (which is in another R project).  I acutally posted today also a pertaining [question ](https://stackoverflow.com/questions/58816599/size-of-interactive-ggiraph-plots-exported-with-htmlwidgets-and-imported-to-blog) on SO and have a little [post ](https://werk.statt.codes/post/size-interactive-plots/#import-widget-and-adjust-sizing) to demonstrate my issue. I think the issue I am struggling with is that the red area changes size depending on the size of the screen and hence distorts the text flow.

**Comment by davidgohel** [comment]
Yes, I saw your SO question. 

Did you see my previous comment? I don't think this is an issue. This is the expected behavior. You have a container and a girafe object with an aspect ratio to respect, the choice has been made to resize it according to container width. If you don't want that resizing, you could use `opts_sizing(rescale=FALSE)` and give your iframe the exact dimensions .

**Comment by zoowalk** [comment]
I see. Thanks again. I guess I am missing something here and my issue might then relate to saveWidget rather than ggiraph. All I want to do is to import a ggigraph into blogdown in a different R project and have it displayed in a way that doesn't introduce excessive space after the plot (irrespective of the screen size). Using a ggriaph plot inside the same R project works totally fine.

**Comment by zoowalk** [comment]
just as to add.. here's the blog which made me realize the issue. If you have time, have a look at this  [graph](https://werk.statt.codes/post/vorzugsstimmen/#difference-leader-and-runners-up)
If the browser is resized (eg. moved to laptop screen) the space under the plot ('padding') grows vertically and distorts the textflow.

**Comment by davidgohel** [comment]
OK. That's not related to `ggiraph::girafe` nor `htmlwidgets::saveWidget`. This is about configuring the iframe you will use. 

To generate the graphic, the following code is OK with no options: 

```
library(tidyverse)
library(ggiraph)
library(htmlwidgets)

my_plot <- mtcars %>% 
  rownames_to_column(., var="name") %>% 
  ggplot()+
  geom_point_interactive(aes(x=wt,
                             y=qsec,
                             tooltip=name))

my_interactive_plot <- girafe(code=print(my_plot), width_svg = 6, height_svg = 5)

saveWidget(x, file="my_widget2.html", background = "red")
```

aspect ratio is 6/5. Then it must be the same ratio for iframe size.

The iframe should be set up like this one 

```
---
title: "Untitled"
output: html_document
---

## R Markdown


<iframe id="inlineFrameExample"
    title="Inline Frame Example"
    width="600"
    height="500"
    frameborder="0" scrolling="no" 
    src="./my_widget2.html">
</iframe>
```

<img width="679" alt="Capture d’écran 2019-11-13 à 10 24 22" src="https://user-images.githubusercontent.com/4331618/68750204-c9489d00-05ff-11ea-968b-fc74fc019d5f.png">

**Comment by zoowalk** [comment]
Many thanks. 

Importing the widget with iframe solved the problem of the excessive vertical space, but introduced a new problem with the graph now exceeding beyond the horizontal borders when resizing the browser since the size is defined in absolute terms, e.g. [here ](https://werk.statt.codes/post/size-interactive-plots/#with-dimensions-defined-in-absolute-terms).  I will see whether the blogdown community has any advice. Thanks again.
