### ISSUE TITLE
Setting scale_y_continuous or coord_cartesian results in set_attr error

### ISSUE THREAD

**Issue by fverkroost** [davidgohel/ggiraph#154]
I have been using ggiraph version 0.6.1. to build interactive world maps (original code on https://rviews.rstudio.com/2019/10/09/building-interactive-world-maps-in-shiny/). Since updating to version 0.7.0, I am getting an error when trying to set y-axis limits using either scale_y_continuous() or coord_cartesian(). The error message says "Warning: Error in set_attr: ids don't have the same length than str (most often, it occurs because of clipping) [No stack trace available]". I have been able to work around this error by subsetting the plotting data to the desired range of y-values and removing scale_y_continuous() or coord_cartesian(), but it would nevertheless be good to be able to combine geom_polygon_interactive() with other ggplot2 functions to set axis limits.

**Comment by davidgohel** [comment]
Hi,

Sorry for the delay. 

> The error message says "Warning: Error in set_attr: ids don't have the same length than str (most often, it occurs because of clipping) [No stack trace available]"

It's a warning there, not an error (that's why you don't see any stack trace).  How are you getting a warning and not an error? This happens because your plot contains polygons that need to be clipped (a polygon is split in two or more polygon) because they don't fit in the defined graphical region. 

> it would nevertheless be good to be able to combine geom_polygon_interactive() with other ggplot2 functions to set axis limits. 

I don't think it is possible to reassign element ids when clipping is occuring (that's why this error has been implemented). The clipping is made by graphical device engine, not by ggplot2. 

----

However, I think by using a better projection, everything should fit in the region and clipping will not be necessary.

You can read these examples: https://github.com/davidgohel/ggiraph/blob/master/examples/geom_sf_interactive.R

They are showing how to use geom_sf_interactive that is easier to use when you need to create maps with ggplot.
