### ISSUE TITLE
Ability to show all tooltips by data_id?

### ISSUE THREAD

**Issue by tsjain** [davidgohel/ggiraph#157]
Hi,

Thanks for the great package. 

Currently one can show tooltip over the hovered point and color others by data_id. Is it possible to show all the tooltips by data_id when one of the members is triggered by hover?

**Comment by sigmapi** [comment]
It's not possible currently, as the tooltip instance is unique.
It could be achieved via javascript as an external custom solution. But how the overlaps would be handled? Depending on the data_id occurrences there could be hundreds of overlapping tooltips. What's the point in that?

**Comment by davidgohel** [comment]
We talk with @sigmapi  and agreed that we can not bring that feature for now. 

`ggiraph` has a defined behavior that we don’t want to hack and fold because we would end with headaches trying to fix issues about a behavior that was not planned when the software has been written.

Maybe one day but not in a short term delay :)
