### ISSUE TITLE
How to increase the solution for downloaded pngs

### ISSUE THREAD

**Issue by zhiiiyang** [davidgohel/ggiraph#176]
Hello, I have a question about increasing the resolution of downloaded png files. Here is an example from the package README page and the figure generated with a resolution of 540X450. Is there a convenient way to have the figure made in a defined (higher) resolution? Thank you!

```
library(ggplot2)
library(ggiraph)
data <- mtcars
data$carname <- row.names(data)

gg_point = ggplot(data = data) +
    geom_point_interactive(aes(x = wt, y = qsec, color = disp,
                               tooltip = carname, data_id = carname)) + 
    theme_minimal()

girafe(ggobj = gg_point)

```

![diagram (1)](https://user-images.githubusercontent.com/7269113/88232503-d86df900-cc2a-11ea-9ea2-65ba03f42bce.png)

**Comment by sigmapi** [comment]
Hi, please use the girafe arguments `width_svg` and `height_svg` to increase the output size / resolution

**Comment by zhiiiyang** [comment]
@sigmapi Thank you. So, I've added these two arguments to the previous code. 

```
library(ggplot2)
library(ggiraph)
data <- mtcars
data$carname <- row.names(data)

gg_point = ggplot(data = data) +
  geom_point_interactive(aes(x = wt, y = qsec, color = disp,
                             tooltip = carname, data_id = carname)) + 
  theme_minimal()

girafe(ggobj = gg_point, width_svg = 10, height_svg = 10)

```
![diagram](https://user-images.githubusercontent.com/7269113/88590895-5279f580-d010-11ea-9f73-c5d2ef26b7b1.png)

The plot is now much bigger but the resolution is still low if you zoom in. Sorry that I am not sure familiar with how height, width and resolution interact with each other here. Should I pass anything to the `dsvg`.

**Comment by sigmapi** [comment]
The resolution of the produced svg from ggiraph is fixed to 72dpi.
Then for the export to png, from the toolbar button, the package [saveSvgAsPng](https://github.com/exupero/saveSvgAsPng) is used, with the quality option set to 1. There is not an option to set the resolution for that.

However this has never been an issue here. I'm not exactly sure what the problem is.

**Comment by zhiiiyang** [comment]
@sigmapi thank you for getting back to me! If `saveSvgAsPng` has set up things in that way, I agree that it could be difficult to have it changed for my case. Yeah, I can quickly introduce the context where we saw this issue. Since we are using `ggiraph` to create massive dynamic graphs in a report, we would like to save the png of interesting results while going through it to save time from remaking them. However, the image quality of the downloaded png format is much different from the svg format. That is why I reached out to you to see if you have any thoughts on it. Does it make sense to you?

**Comment by sigmapi** [comment]
Yes, I understand. To produce better png quality, you'd have to generate a quite large png.
However this is not the method to use, because browsers have limitations, as you can see at the end of saveSvgAsPng readme. 

In your case, I'd implement an extra download button which would use `dsvg` or `svg` functions to save the desired plot with a quite large size.

**Comment by zhiiiyang** [comment]
@sigmapi, thank you for the suggestions! I will give it a try.
