### ISSUE TITLE
Using computed variables in geom_smooth_interactive

### ISSUE THREAD

**Issue by brooksambrose** [davidgohel/ggiraph#180]
First thanks for a great package! I'm wondering why in principle it shouldn't be possible to use computed variables as tooltips in `geom_smooth_interactive`. For instance:

```r
girafe(ggobj=ggplot(mpg, aes(displ, hwy)) + geom_smooth_interactive(aes(color=stat(y))))
```

Correctly displays the computed variable `stat(y)` as a coloring of the line. However, using it with the tooltip throws an error:

```
> girafe(ggobj=ggplot(mpg, aes(displ, hwy)) + geom_smooth_interactive(aes(color=stat(y),tooltip=stat(round(y,1)))))
`geom_smooth()` using method = 'loess' and formula 'y ~ x'
Error: Aesthetics can not vary with a ribbon
```

It seems natural to want to display the fitted value `stat(y)` as a tooltip when hovering over the smoother. I realize I could kludge this by precalculating the smoother, however it would be nice to use the convenience features built into ggplot2.

https://github.com/davidgohel/ggiraph/blob/10e68f3eda40b220004729141b0a4b729f2a6daa/R/geom_ribbon_interactive.R#L47

**Comment by sigmapi** [comment]
Sorry for the delayed response. The problem is that the geometry here is a line, actually multiple line segments, as you can see by inspecting the result svg element. 
Coloring with stat(y) works because ggplot2 calculates the color for each segment (using the edge points).
But to create a tooltip based on y is not possible. A line segment svg element can have one tooltip as a whole and using y would produce multiple variations based on y. That's why you get this error.
You can use another variable for tooltip, which produces a single tooltip for a segment.
Alternatively you can smooth the data before hand and add a point layer with tooltip info for each point.
