### ISSUE TITLE
Problems when using geom_label/text_interactive with use_fill

### ISSUE THREAD

**Issue by corriebar** [davidgohel/ggiraph#183]
I'm making a stacked area chart and want to add some annotations. I'm using ggiraph to add tooltips on hover that are in the same color as the area they belong to by using `use_fill=T`. This works great for the area chart, however it fails in an unexpected way for the text/label. I'm using white text and would expect the tooltip to have the same background color as the given by the fill argument but the tooltip becomes white itself and hence unreadable. For some weird reason this does not happen when having black text instead.

```r
library(tidyverse)
library(ggiraph)
set.seed(2020)
time <- as.numeric(rep(seq(1,7),each=7))  # x Axis
value <- runif(49, 10, 100)               # y Axis
group <- rep(LETTERS[1:7],times=7)        # group, one shape per group
data <- data.frame(time, value, group)

annotation <- data.frame(time = c(3, 6.5), value = c(50, 350),
                         group = c("F", "B"))

# stacked area chart
plot <- ggplot(data, aes(x=time, y=value, fill=group)) + 
  geom_density_interactive(stat = "identity", position = "stack",
                           aes(tooltip = group)) +
  geom_label_interactive(data = annotation,
                          label.size = NA,
                         aes(label = group, 
                             tooltip = paste("This is the ", group)),
                         color = "white")
plot
girafe(ggobj = plot,
       options = list(opts_tooltip(use_fill =T,
                                   use_stroke = F)) )
```
![image](https://user-images.githubusercontent.com/11877945/97203442-1abc4e80-17b5-11eb-8578-b1a898b95e90.png)
When hovering over the section just next to the text (when using geom_label), the tooltip background is in the right color:
![image](https://user-images.githubusercontent.com/11877945/97203622-5d7e2680-17b5-11eb-914b-c22bb2dabcc7.png)
Curiously, the problem does not happen when setting `color = "black"` in the code above.

**Comment by BriceNocenti** [comment]
Hi, I get the same kind of problem with geom_label_interactive and use_fill = TRUE : when hovering over the text, the background color of the tooltip is the same color as the text, which is what I wanted ; but just some pixels away, when hovering over the white background of the label, the tooltip goes white (when you point at the label, it is randomly colored or white depending where the mouse exactly is). It’s certainly because the label must be composed of two objets, a text and an area  : maybe keeping the hover effect for the text, and discarding it for the area, would ensure more constant behavior.

**Comment by sigmapi** [comment]
Thanks for the report. 
The problem here is that for svg text elements, the "fill" is the "color" that you specify in geom_text/label_interactive.
Effectively the background color of the tooltip becomes "white" when the text color is set as "white".

We'll need to do some thinking to decide how to handle this situation.
