### ISSUE TITLE
strange bug: download link on chart not working under certain circumstances

### ISSUE THREAD

**Issue by neuwirthe** [davidgohel/ggiraph#189]
ggiraph version 0.7.8
With the following code

```
my_df <-
  tibble(x=rep(1:10,2),
       y=c(1:10,2:11),
       f=rep(c("<a","b"),each=10))
```

```
my_df %>%
  ggplot(aes(x=x,y=y,
             color=f,
             data_id=f,
             tooltip=f)) +
  geom_line_interactive() ->
  chart
girafe(ggobj=chart)
```

The chart will have a download icon in the upper right corner, but the icon will not work. Clicking on it will not produce an action.
The culprit is the string "<a". When any of the values of f begins with "<", the icon does not work.

<img width="253" alt="2021-03-06_02-30-37" src="https://user-images.githubusercontent.com/157619/110190724-00f6dc00-7e25-11eb-8bc4-ff4279fa2179.png">

Without the "<", the icon on the chart will work.

```
my_df <-
  tibble(x=rep(1:10,2),
       y=c(1:10,2:11),
       f=rep(c("a","b"),each=10))
```

```
my_df %>%
  ggplot(aes(x=x,y=y,
             color=f,
             data_id=f,
             tooltip=f)) +
  geom_line_interactive() ->
  chart
girafe(ggobj=chart)
```

**Comment by sigmapi** [comment]
Hi, the failure is occurring in the svg-as-png javascript utility, which is used to convert the result svg to a png image.
The reason is the presence of character `<` in the `data_id` attribute.
The contents of the `tooltip` attribute are always html-escaped, but the `data_id` are not.
Attribute `data_id` is used as an html identifier and it should not contain problematic characters.

The solution is to manually html-escape the data_id:
```
my_df %>%
  ggplot(aes(x=x,y=y,
             color=f,
             data_id=htmltools::htmlEscape(f),
             tooltip=f)) +
  geom_line_interactive() ->
  chart
girafe(ggobj=chart)
```

**Comment by sigmapi** [comment]
Closing this
