### ISSUE TITLE
Add IDs and/or classes in as many places as possible

### ISSUE THREAD

**Issue by gadenbuie** [davidgohel/ggiraph#246]
First, I love ggiraph. So thank you! I love that it's a very lightweight way to make a ggplot plot interactive. I also really like that the inlined-svg becomes an excellent starting point for highly-customized interactive plots.

One feature that would make it even easier to build on ggiraph plots would be to add classes and IDs throughout the plot in as many places as possible. I'll admit I haven't looked at ggiraph's implementation, so I'm not sure how feasible my suggestion is. 

Here are a few places I wish I could have had a class or ID to hook into:

1. The `id` of the ggiraph plot should be customizable. Currently, a UUID is used, which certainly guarantees uniqueness and is a sensible default, but hampers customization. I've had to wrap ggiraph plots in containers with IDs and target them with rules like `#my-id .girafe_container_std`.

1. Tooltips could have stable class names, e.g. `.girafe_tooltip`. You could keep the `.tooltip_svg_{id}` class or move the linking ID to a data attrribute, e.g. `data-for="{id}"`. This would allow broad rules to target all tooltips, or specific styling via the`.girafe_tooltip[data-for="{id}"]` selector.

1. Individual layers could have both classes and IDs. For example, layers created with `geom_point_interactive()` could have a `.girafe_geom_point` class. For extensibility, it'd be awesome if `geom_point_interactive()` could take `class` and `id` arguments that could be added to the default classes. Right now, I'm using CSS rules based on static colors used for the geom, e.g. `.girafe_container_std circle[fill="#595959"]` to target a `geom_point()` layer.

1. Similarly, it'd be very helpful if standard plot elements could include classes as well. Things like the plot background, axis lines, strip titles, legends, etc. That would go a long way toward targeting those elements with CSS rules or JavaScript event listeners.

**Comment by davidgohel** [comment]
Hello,

Thanks. And sorry for the delay. 

I started documenting your questions here: https://davidgohel.github.io/ggiraph/extra-ipar.html. (Let us know if something unclear, we want to improve the documentation... This is available since a long time and it was not documented until last week).

The main page has also been enriched with more details about how to add interactivity to panel content, scales, strips, and theme elements: https://davidgohel.github.io/ggiraph/starting.html#interactive-geoms, 

A code like the following is a basic example of how to add an extra attribute named "class" to the final SVG.

```
p1 + labs(title = "This is an interactive title") +
  theme(
    plot.title = element_text_interactive(
      data_id = "plot.title",
      tooltip = "plot title",
      hover_css = "fill:red;stroke:none;",
      class = "zzzzz",
      extra_interactive_params = "class"
    )
  )
```
The same applies to scales, geoms, labeller.

So it should answer 1, 3 and 4 :)
 
About the 2, yes, it makes sense. We can add this option, this could help to reduce CSS in the code that can be sometimes scary for the non-HTML savvy.
