### ISSUE TITLE
Responsive charts with ggiraph 0.4.0? 

### ISSUE THREAD

**Issue by d-qn** [davidgohel/ggiraph#66]
Hello,

thank you again for this great package. 

However since upgrading to ggiraph 0.4.0, I am no longer able to create responsive ggiraph charts. Looking at your [ggiraph sizing post](https://davidgohel.github.io/ggiraph/articles/sizing.html), I understand that the width argument is no longer used. But is there any way to have horizontally responsive chart (as it was previously)? 

I have tried rewriting the `sizingPolicy$defaultWidth` of a ggiraph object, but it has no effects.

**Comment by Rozenn** [comment]
Hi, I have also issues to manage plot sizes when using in Shiny. 
Before package update, I used width argument, which is no longer used. 
As you can see in the file error_graph_size1, there is a big space below my graph, which is (probably) due to the style "padding-top:100%", which is added automatically. When I remove it manually, the size is OK. but because it's a specific style of an element and not in a class, I can't manage to put padding-top as 0... What is the best way to deal with responsive charts ??

**Comment by davidgohel** [comment]
I am off but this is on the top of the todo list

**Comment by davidgohel** [comment]
Hi,

I think it's fixed with the github version. Could you check? 

David

**Comment by d-qn** [comment]
Thanks David. I am currently off, but I will check it next week.

**Comment by felixgrossmann** [comment]
Hi David,

at first: thank you for this awesome package!

I already contacted you on twitter about this topic: https://stackoverflow.com/questions/45191999/ggiraph-plot-doesnt-resize-to-fit-the-page . I installed the latest github version of ggiraph and unfortunately the issue about the responsive resizing remains. I hope the information in the SO post is enough. Please contact me if you need more information.

Thanks in advance!
Felix

**Comment by d-qn** [comment]
Hi David, 

tested ggiraph 0.4.9003 from github. I have not tested any shiny use, but standalone ggiraph graphics are now responsive thank you.

**Comment by davidgohel** [comment]
Thanks @d-qn for your patience :)

@Rozenn I think it's another issue, I will move your description in a new issue later today. 

@felixgrossmann idem, I will open a new ticket as it is another issue.
